### ISSUE TITLE
Fix for the vanishing Sidebar

### ISSUE THREAD

**Issue by Skyhero-admin** [Skyhero-admin/Skyhero-admin.github.io#1]
When I reduce the width of the browser to see if it is responsive it changes the layout as per the media queries which is good.
And when I click on the socials button on top left of the screen it shows the side bar. Now here's the issue that when I close the sidebar in the small width browser and later when I maximize the browser then the side bar is missing there 

Ya'll can try it for yourself at https://skyhero-admin.github.io/

here are some screenshots for reference 
![Screenshot from 2021-05-17 19-59-26](https://user-images.githubusercontent.com/74371107/118507515-ef4a8280-b74b-11eb-92d7-9724b59cc8be.png)
![Screenshot from 2021-05-17 19-59-31](https://user-images.githubusercontent.com/74371107/118507536-f2de0980-b74b-11eb-9bca-b6c6a148179e.png)
This is how it looks when I maximize it again, the empty space on the left is where the sidebar is supposed to be
![Screenshot from 2021-05-17 19-59-39](https://user-images.githubusercontent.com/74371107/118507546-f5406380-b74b-11eb-9858-e3328f781704.png)
I would appreciate it if someone could guide me on how to fix this since I am new to css and javascript and don't know much about how toggle functions work

**Comment by ashwinexe** [comment]
Hi @Skyhero-admin Its a good portfolio. 
The reason sidebar was not visible is because the `visibility : hidden` property stayed even after resizing back to desktop view.
It can be solved by adding an `onresize( )` event to body tag and linking it to a function where you can check screen width and show/hide the element as width changes.
![image](https://user-images.githubusercontent.com/53075480/118589842-d4fdbc80-b7be-11eb-8a4f-44d6aa76dae6.png)

**Comment by Skyhero-admin** [comment]
ooh
Thanks I didn't even know that there was something like onresize( ) 😅
I tried it and it seems to work 😁 
Thanks a lot for the help

**Comment by Skyhero-admin** [comment]
Please do give feedback later if you have any suggestions for this

**Comment by ashwinexe** [comment]
Great, on a side note I see the functions on your javascript are bit complex, try breaking the functions so that one does only a fixed task, this way its easy to debug and read the code. I'm gonna create a pull request to show your some difference (bit still prefer if you try on your own once to get better idea)

**Comment by Skyhero-admin** [comment]
ohk

**Comment by Skyhero-admin** [comment]
> Great, on a side note I see the functions on your javascript are bit complex, try breaking the functions so that one does only a fixed task, this way its easy to debug and read the code. I'm gonna create a pull request to show your some difference (bit still prefer if you try on your own once to get better idea)

I tried adding the functions in a more cleaner way according the the PR that you made as it gave me an idea on how to go about it 😁

I may not have much knowledge but I would like to help on some of your projects as well

**Comment by Skyhero-admin** [comment]
#3 closed this issue
